name: ecommerce_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.3
  flutter_svg: ^2.1.0
  flutter_localization: ^0.3.2
  dots_indicator: ^4.0.1
  shared_preferences: ^2.5.3
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_assets: ^0.0.6


flutter:
  uses-material-design: true
  assets:
    - assets/logo/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 500
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/market Logo.png"

flutter_assets:
  assets_path: assets/logo/
  output_path: lib/core/utils
  filename: app_images.dart
  class_name: AppImages
  class_name_prefix: App

flutter_intl:
  enabled: true
